Project/Models/SaleCoin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Models
{
    public class SaleCoin
    {
        [Required]
        public string Id { get; set; }
        [Required]
        public string PaypalEmail { get; set; }
        [Required]
        public double amountcoin { get; set; }
        [Required]
        public bool TransactionStatus { get; set; }
        [Required]
        [ForeignKey("ApplicationUserId")]
        public string ApplicationUserId { get; set; }
        [Required]
        public ApplicationUser ApplicationUser { get; set; }
        public DateTime DateCreate { get; set; } = DateTime.Now;
    }
}

Project/Areas/Customers/Controllers/SaleCoinController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project.Extensions;
using Project.Models;
using Project.Models.Dtos;
using Project.Repositorys.IRepository;
using Project.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Areas.Customers.Controllers
{
    [Area("Customers")]
    [Authorize(Roles = UserRole.Customers)]
    [Route("[controller]/")]
    public class SaleCoinController : Controller
    {
        private readonly ISaleCoinRepository _saleCoinRepository;
        private readonly IUserRepository _userRepository;
        private readonly IMapper _mapper;
        public SaleCoinController(ISaleCoinRepository saleCoinRepository, IUserRepository userRepository, IMapper mapper)
        {
            _saleCoinRepository = saleCoinRepository;
            _userRepository = userRepository;
            _mapper = mapper;
        }
        [Route("Create")]
        public async Task<IActionResult> Create()
        {
            return await Task.Run(() => View());
        }
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SaleCoinDtos saleCoinDtos)
        {
            if (!ModelState.IsValid)
                return await Task.Run(() => View());

            if (saleCoinDtos == null)
            {
                return BadRequest(ModelState);
            }
            var username = await _userRepository.getUserByIdAsync(User.GetUserId());

            if(saleCoinDtos.amountcoin < 0 || saleCoinDtos.amountcoin > username.coin) {
                return BadRequest();
            }

            var SaleCoinOrderId = Guid.NewGuid();

            SaleCoinDtos model = new SaleCoinDtos
            {
                Id = SaleCoinOrderId.ToString(),
                PaypalEmail = saleCoinDtos.PaypalEmail,
                amountcoin = saleCoinDtos.amountcoin,
                TransactionStatus = false,
                ApplicationUserId = User.GetUserId()
            };

            var SaleCoinObj = _mapper.Map<SaleCoin>(model);

            if (!_saleCoinRepository.CreateSaleCoin(SaleCoinObj))
            {
                ModelState.AddModelError("", $"Something went wrong when saving the record");
                return StatusCode(500, ModelState);
            }

            username.coin -= Convert.ToInt32(model.amountcoin);

            if (!_userRepository.UpdateAppUser(username))
            {
                ModelState.AddModelError("", $"Something went wrong when saving the record");
                return StatusCode(500, ModelState);
            }

            return await Task.Run(() => RedirectToAction("Details",new { id = SaleCoinOrderId}));
        }
        [Route("Details/{id?}")]
        public async Task<IActionResult> Details(string id)
        {
            var model = await _saleCoinRepository.GetSaleCoin(id, User.GetUserId());

            var result = _mapper.Map<SaleCoinDtos>(model);
            return await Task.Run(() => View(result));
        }
        [Route("History")]
        public async Task<IActionResult> History()
        {
            var model = await _saleCoinRepository.GetSaleCoins(User.GetUserId());

            var result = _mapper.Map<List<SaleCoinDtos>>(model);
            return await Task.Run(() => View(result));
        }
    }
}

Project/Areas/Customers/Views/SaleCoin/Create.cshtml
@model Project.Models.Dtos.SaleCoinDtos
@{
    ViewData["Title"] = "Create";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<style>
    .InputCoin {
        margin-bottom: auto;
        height: 70px;
        background-color: #fff;
        padding: 10px
    }

    .search-input {
        color: white;
        border: 0;
        outline: 0;
        background: none;
        width: 0;
        margin-top: 5px;
        caret-color: transparent;
        line-height: 40px;
        transition: width 0.4s linear
    }

    .InputCoin .search-input {
        padding: 0 10px;
        width: 550px;
        caret-color: #536bf6;
        font-size: 21px;
        font-weight: 300;
        color: black;
        transition: width 0.4s linear
    }

    .search:hover > .search-icon {
        background: #1A237E;
        color: #fff
    }

    .search-icon {
        height: 50px;
        width: 50px;
        float: right;
        display: flex;
        justify-content: center;
        align-items: center;
        color: white;
        background-color: #536bf6
    }

    a:link {
        text-decoration: none
    }

    .container1 {
        background-color: #eeeeee;
    }

    .col-6 {
        margin-top: 35px;
    }
</style>
<div class="container-fluid" style="background-color: #eeeeee;">
    <div class="container p-5">
        <div class="d-flex justify-content-center h-100">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="InputCoin" style="border-radius: 10px;">
                    <input type="email" asp-for="PaypalEmail" class="search-input" placeholder="Nhập Paypal Email..." style="width: 40%; border-right: 4px solid red;">
                    <span asp-validation-for="PaypalEmail" class="text-danger"></span>
                    <input type="number" min="1" asp-for="amountcoin" class="search-input" placeholder="Nhập số xu cần rút..." style="width: 40%;">
                    <span asp-validation-for="amountcoin" class="text-danger"></span>
                    <button type="submit" class="search-icon" style="border-radius: 7px;">
                        <i class="fas fa-search-dollar"></i>
                    </button>
                </div>
            </form>
        </div>

    </div>
</div>

Project/Areas/Customers/Views/SaleCoin/Details.cshtml
@model Project.Models.Dtos.SaleCoinDtos


@{
    ViewData["Title"] = "Details";
}
<style>
    .container-fluid {
        margin-top: 200px
    }

    p {
        font-size: 14px;
        margin-bottom: 7px
    }

    .small {
        letter-spacing: 0.5px !important
    }

    .card-1 {
        box-shadow: 2px 2px 10px 0px rgb(190, 108, 170)
    }

    hr {
        background-color: rgba(248, 248, 248, 0.667)
    }

    .bold {
        font-weight: 500
    }

    .change-color {
        color: #AB47BC !important
    }

    .card-2 {
        box-shadow: 1px 1px 3px 0px rgb(112, 115, 139)
    }

    .fa-circle.active {
        font-size: 8px;
        color: #AB47BC
    }

    .fa-circle {
        font-size: 8px;
        color: #aaa
    }

    .rounded {
        border-radius: 2.25rem !important
    }

    .progress-bar {
        background-color: #AB47BC !important
    }

    .progress {
        height: 5px !important;
        margin-bottom: 0
    }

    .invoice {
        position: relative;
        top: -70px
    }

    .Glasses {
        position: relative;
        top: -12px !important
    }

    .card-footer {
        background-color: #AB47BC;
        color: #fff
    }

    h2 {
        color: rgb(78, 0, 92);
        letter-spacing: 2px !important
    }

    .display-3 {
        font-weight: 500 !important
    }

    @@media (max-width: 479px) {
        .invoice {
            position: relative;
            top: 7px
        }

        .border-line {
            border-right: 0px solid rgb(226, 206, 226) !important
        }
    }

    @@media (max-width: 700px) {
        h2 {
            color: rgb(78, 0, 92);
            font-size: 17px
        }

        .display-3 {
            font-size: 28px;
            font-weight: 500 !important
        }
    }

    .card-footer small {
        letter-spacing: 7px !important;
        font-size: 12px
    }

    .border-line {
        border-right: 1px solid rgb(226, 206, 226)
    }

    .container1 {
        height: 265px;
    }
</style>
<div class="container-fluid my-5 d-flex justify-content-center">
    <div class="card card-1" style="width: 700px;">
        <div class="card-header bg-white">
            <div class="media flex-sm-row flex-column-reverse justify-content-between ">
                <div class="col my-auto">                    
                    <h4 class="mb-0">Hóa đơn rút xu, của<span class="change-color"> @Model.ApplicationUser.LastName</span> !</h4>
                </div>
                <div class="col-auto text-center my-auto pl-0 pt-sm-4">
                    <img class="img-fluid my-auto align-items-center mb-0 pt-3" src="~/images/Coin/coin-default.jpg" width="115" height="115">
                    <p class="mb-4 pt-0 Glasses">Shop Coin</p>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row justify-content-between mb-3">
                <div class="col-auto">
                    <h6 class="color-1 mb-0 change-color">Biên Lai</h6>
                </div>
            </div>
                <div class="row mt-4">
                    <div class="col">
                        <div class="card card-2">
                            <div class="card-body">
                                <div class="media">
                                    <div class="sq align-self-center "> <img class="img-fluid my-auto align-self-center mr-2 mr-md-4 pl-0 p-0 m-0" src="~/images/Coin/coin-default.jpg" width="135" height="135"> </div>
                                    <div class="media-body my-auto text-right">
                                        <div class="row my-auto flex-column flex-md-row">
                                            <div class="col-auto my-auto ">
                                                <h6 class="mb-0"> @Model.amountcoin Xu</h6>
                                            </div>
                                            <div class="col my-auto "> <small>@Model.PaypalEmail </small></div>
                                            <div class="col my-auto "><small>
                                                Status: 
                                                @if (Model.TransactionStatus is true)
                                                {
                                                    <span class="badge badge-success">Đã Chuyển</span>
                                                }
                                                else
                                                {
                                                    <span class="badge badge-info">Đang chờ</span>
                                                }
                                                </small>
                                            </div>
                                            <div class="col my-auto ">
                                                <h6 class="mb-0">$@Model.amountcoin</h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr class="my-3 ">
                            </div>
                        </div>
                    </div>
                </div>
            <div class="row mt-4">
                <div class="col">
                    <div class="row justify-content-between">
                        <div class="col-auto">
                            <p class="mb-1 text-dark"><b>Chi tiết hóa đơn</b></p>
                        </div>
                        <div class="flex-sm-col text-right col">
                            <p class="mb-1"><b>Tổng tiền</b></p>
                        </div>
                        <div class="flex-sm-col col-auto">
                            <p class="mb-1">$@Model.amountcoin</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row invoice ">
                <div class="col" style="padding-top: 70px;">
                    <p class="mb-1"> Mã số hóa đơn : @Model.Id</p>
                    <p class="mb-1"> Ngày rút Xu  : @Model.DateCreate</p>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="jumbotron-fluid">
                <div class="row justify-content-between ">
                    <div class="col-sm-auto col-auto my-auto"><img class="img-fluid my-auto align-self-center " src="https://i.imgur.com/7q7gIzR.png" width="115" height="115"></div>
                    <div class="col-auto my-auto ">
                        <h2 class="mb-0 font-weight-bold">Tổng tiền rút</h2>
                    </div>
                    <div class="col-auto my-auto ml-auto">
                        <h1 class="display-3 ">$@Model.amountcoin</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Project/Areas/Customers/Views/SaleCoin/History.cshtml
@model IEnumerable<Project.Models.Dtos.SaleCoinDtos>

@{
    ViewData["Title"] = "OrderHistory";
    int count = 1;
}

<!-- Datatable CSS -->
<link type="text/css" rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css"/>
<style>
   .container1{
       height: 220px;
   }
</style>
<div class="container mt-5" style="padding: 60px;">  
    <h2 style="padding-bottom: 10px;"> Lịch sử giao dịch </h2> 
    <div class="row">
        <div class="nav nav-tabs mb-4" id="nav-tab" role="tablist">
          <a class="nav-item nav-link" data-toggle="tab" asp-action="OrderHistory" asp-controller="Order" asp-area="Customers">Hóa đơn mua xu</a>
          <a class="nav-item nav-link active show" id="nav-profile-tab" href="#">Hóa đơn rút xu</a>
        </div>

            <div class="col-md-12">
                    <table id="myTable" class="table">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th>Hóa đơn #</th>
                                <th>Email rút</th>
                                <th>Trạng thái</th>
                                <th>Tổng giá rút</th>
                                <th>Ngày rút xu</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody class="table-body">
                            @foreach (var item in Model)
                            {
                                <tr class="cell-1">
                                    <td class="text-center">@count</td>
                                    <td>#@item.Id.Substring(0, 8)</td>
                                    <td>@(item.PaypalEmail)</td>
                                    @if (item.TransactionStatus is true)
                                    {
                                        <td><span class="badge badge-success">Đã Chuyển</span></td>
                                    }
                                    else
                                    {
                                        <td><span class="badge badge-info">Đang chờ</span></td>
                                    }

                                    <td>$@item.amountcoin</td>
                                    <td>@item.DateCreate</td>
                                    <td>
                                        <a asp-controller="SaleCoin" asp-action="Details" asp-route-id="@item.Id" class="icon-block">
                                            <i class="fa fa-ellipsis-h text-black-50"></i>
                                        </a>
                                    </td>
                                </tr>
                                count++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
</div>

@section Scripts{
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                "language": {
                    "lengthMenu": 'Hiện thị  <select>' +
                        '<option value="10">10</option>' +
                        '<option value="20">20</option>' +
                        '<option value="30">30</option>' +
                        '<option value="40">40</option>' +
                        '<option value="50">50</option>' +
                        '<option value="-1">All</option>' +
                        '</select> Dòng',
                    "search": "Tìm:",
                    "info": "Hiển thị _START_ đến _END_ của _TOTAL_ mục",
                    "paginate": {
                        "next": "Tới",
                        "previous": "Lùi lại"
                    }
                }
            });
        });
    </script>
}